package simulator

// The report is the product of this package: everything else exists so that the
// numbers ТЗ 16.4 puts ceilings on, plus the membership and routing behaviour those
// ceilings are supposed to make affordable, can be stated with a provenance.
//
// docs/LOADTEST.md is generated by this file rather than written by hand for one
// reason: the numbers in it must be the numbers a run produced, and a hand-copied
// table is how a report starts disagreeing with the code that made it.

import (
	"fmt"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

// KindStat is one traffic category's share of the per-node rate.
type KindStat struct {
	Kind       Kind
	SendBytes  int64
	RecvBytes  int64
	KbitIdle   float64
	KbitActive float64
}

// PhaseReport is one phase's measured rates and its verdict against the ceiling that
// applies to it.
type PhaseReport struct {
	Phase   string
	Beats   int
	Seconds int64

	KbitIn      float64
	KbitOut     float64
	KbitService float64 // ТЗ 16.4's служебный трафик: everything but task traffic
	KbitTask    float64
	KbitPeak    float64 // worst single gossipsub heartbeat, worst node

	// Ceiling and verdict. The idle phase is judged on KbitService, because the
	// specification bounds gossip overhead in peace time; the active phases are
	// judged on the total, because that is the state the second ceiling describes.
	Ceiling float64
	Verdict string
	Detail  string
}

// VerdictRu is the verdict in the wording a report is read in: a ceiling missed is
// stated as «НЕ выполнен», not as a number rounded until it fits.
func (p PhaseReport) VerdictRu() string {
	if p.Verdict == "PASS" {
		return "выполнен"
	}
	return "НЕ выполнен"
}

// Result is one mesh size's full answer.
type Result struct {
	Nodes int
	Seed  int64
	P     Params
	Ph    Phases

	Idle    PhaseReport
	Active  PhaseReport
	Failure PhaseReport

	Kinds []KindStat

	// Membership shape and stability.
	MeshPeers    float64
	Links        float64
	Routable     float64
	RoutableFrac float64
	ViewSize     float64
	ViewFrac     float64
	FreshIdle    float64
	FreshActive  float64
	FreshRecover float64
	FreshMin     float64

	// Discovery speed.
	LagP50Ticks float64
	LagP95Ticks float64
	LagP50Beats float64
	MaxLagTicks int32

	// Gossipsub and node mechanics.
	Grafts        int64
	Prunes        int64
	IhaveFrames   int64
	IwantFrames   int64
	IdontFrames   int64
	Handshakes    int64
	PeerExchanges int64
	SkillSyncs    int64
	Lookups       int64
	Deliveries    int64
	Edges         int64
	DialCapped    int64
	RejectedState int64
	SyncMsgs      int64
	SyncStates    int64
	PeakInflight  int64

	// Stabilisation, in node heartbeats: the earliest heartbeat at which any node's view
	// was complete, and at which every entry of it was inside the expiry horizon — from
	// the start of the run in the idle phase, and from the crash in the failure phase.
	// -1 means no node got there inside the window, which the report prints as such.
	StabFullBeats, StabFreshBeats       float64
	RecoverFullBeats, RecoverFreshBeats float64

	// Repair and loss accounting, quoted by the invariants and the boundaries section.
	RepairCopies   int64
	Unrepaired     int64
	LostInflight   int64
	MaxSyncBatches int
	// DupSuppressions is how many forwarded copies the model did not bill because the
	// recipient had already accepted the message. It is the undercount boundary note 2
	// quotes, in frames rather than bytes.
	DupSuppressions int64
	TotalSendBytes  int64
	TotalRecvBytes  int64

	// Tasks.
	TasksInjected int
	TasksLocal    int
	TasksRouted   int
	TasksNoWorker int
	TasksLost     int
	LostReasons   map[string]int
	HopsMean      float64
	RouteP50      float64
	RouteP95      float64
	RouteP99      float64

	// Behaviour under a 10 % failure.
	Crashed         int
	ConnectivityPre float64
	ConnectivityMin float64
	ConnectivityEnd float64
	ExpireBeats     float64
	RebuildP50      float64
	RebuildP95      float64
	RebuildMax      float64
	LostEntries     int64
	RejoinEntries   int64

	// Wire costs, measured with proto.Marshal from gen/zeptomesh/v1.
	SizeOwnGossip int
	SizeSyncBatch int
	SizeEnvelope  int
	SizeAck       int
	SizeResult    int
	SizeCapsRT    int
	SizePxRT      int
	SizeID        int

	// Cost of the run itself. The model measures a protocol, not a machine, so these
	// are recorded by whoever drove Run() rather than by the Sim: a simulation cannot
	// time itself from inside the loop it is timing. Zero means "not measured", and
	// the report prints that instead of a plausible number.
	Wall time.Duration
	// PeakRSSKb is the process's VmHWM read after this run. It is a high-water mark
	// for the whole process, not for one size, so a multi-size report's last column is
	// the run's overall peak; the detail says so.
	PeakRSSKb int64

	Verdict string
}

// kbit converts a byte count accumulated over a window into per-node kilobits per
// second. Кбит is 1000 bits, not 1024, because the specification states a network
// budget rather than a storage quantity.
func kbit(bytes int64, nodes int, seconds int64) float64 {
	if nodes <= 0 || seconds <= 0 {
		return 0
	}
	return float64(bytes) * 8 / float64(nodes) / float64(seconds) / 1000
}

func mean(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	var s float64
	for _, v := range a {
		s += v
	}
	return s / float64(len(a))
}

func pctl(a []float64, q float64) float64 {
	if len(a) == 0 {
		return 0
	}
	s := append([]float64(nil), a...)
	sort.Float64s(s)
	if q <= 0 {
		return s[0]
	}
	if q >= 1 {
		return s[len(s)-1]
	}
	return s[int(q*float64(len(s)-1))]
}

func verdictOf(measured, ceiling float64) string {
	if measured <= ceiling {
		return "PASS"
	}
	return "FAIL"
}

func verdictDetail(measured, ceiling float64) string {
	if measured <= ceiling {
		return fmt.Sprintf("%.1f из %.0f Кбит/с (%.0f%% потолка)", measured, ceiling, 100*measured/ceiling)
	}
	return fmt.Sprintf("%.1f Кбит/с при потолке %.0f — превышение в %.1f раза",
		measured, ceiling, measured/ceiling)
}

// phaseAggregate sums the per-node, per-kind, per-phase byte counters over the live
// nodes.
func (s *Sim) phaseAggregate(pi int) (send, recv, svcSend, svcRecv, task int64) {
	for _, nd := range s.nodes {
		for k := Kind(0); k < KindCount; k++ {
			send += nd.phaseKind[pi][k][0]
			recv += nd.phaseKind[pi][k][1]
			if k == KindTask {
				task += nd.phaseKind[pi][k][0] + nd.phaseKind[pi][k][1]
				continue
			}
			svcSend += nd.phaseKind[pi][k][0]
			svcRecv += nd.phaseKind[pi][k][1]
		}
	}
	return
}

// summarize turns the run's counters and series into a Result.
// beatsOf converts a beat index to elapsed node heartbeats, keeping -1 (never reached)
// negative so a caller cannot print it as "instantly".
func beatsOf(s *Sim, beat int32) float64 {
	if beat < 0 {
		return -1
	}
	return float64(beat)
}

func (s *Sim) summarize() *Result {
	// The run ends with copies still scheduled. Each was billed to a sender and will
	// never reach a receiver inside the window, which is exactly what lostInflight
	// counts; reporting them is what makes Σrecv == Σsend − Σloss a check rather than a
	// tautology of the phase windows.
	s.lostInflight += s.inflightBytes
	idleBeats := int32(max(s.ph.IdleBeats, 1))
	activeBeats := int32(max(s.ph.ActiveBeats, 1))
	failureBeats := int32(max(s.ph.FailureBeats, 1))
	idleEnd := idleBeats * s.ticksPerBeat
	activeEnd := idleEnd + activeBeats*s.ticksPerBeat

	phase := func(pi int, beats int32, name string, ceiling float64) PhaseReport {
		sec := int64(beats) * int64(s.ticksPerBeat) * s.tickSeconds()
		send, recv, svcSend, svcRecv, task := s.phaseAggregate(pi)
		pr := PhaseReport{
			Phase: name, Beats: int(beats), Seconds: sec,
			KbitIn:      kbit(recv, s.n, sec),
			KbitOut:     kbit(send, s.n, sec),
			KbitService: kbit(svcSend+svcRecv, s.n, sec),
			KbitTask:    kbit(task, s.n, sec),
			KbitPeak:    s.tickPeak[pi],
			Ceiling:     ceiling,
		}
		switch name {
		case PhaseIdle:
			pr.Verdict = verdictOf(pr.KbitService, ceiling)
			pr.Detail = verdictDetail(pr.KbitService, ceiling)
		default:
			pr.Verdict = verdictOf(pr.KbitIn+pr.KbitOut, ceiling)
			pr.Detail = verdictDetail(pr.KbitIn+pr.KbitOut, ceiling)
		}
		return pr
	}
	idle := phase(phaseIdleIdx, idleBeats, PhaseIdle, CeilingKbitIdle)
	active := phase(phaseActiveIdx, activeBeats, PhaseActive, CeilingKbitActive)
	fail := phase(phaseFailIdx, failureBeats, PhaseFailure, CeilingKbitActive)

	mIdle := meanSeries(s.samp, 0, idleEnd)
	mActive := meanSeries(s.samp, idleEnd, activeEnd)
	mFail := meanSeries(s.samp, activeEnd, s.tick)

	r := &Result{
		Nodes: s.n, Seed: s.seed, P: s.p, Ph: s.ph,
		Idle: idle, Active: active, Failure: fail,
		Kinds: s.kindStats(),

		MeshPeers: mActive.MeshPeers, Links: mActive.Links,
		Routable:     mActive.Routable,
		RoutableFrac: mActive.Routable / max(mActive.ViewTarget, 1),
		ViewSize:     mActive.ViewSize,
		ViewFrac:     mActive.ViewSize / max(mActive.ViewTarget, 1),
		FreshIdle:    mIdle.Fresh, FreshActive: mActive.Fresh,
		FreshRecover: mFail.Fresh, FreshMin: s.freshMin,

		LagP50Ticks: pctl(s.lag, 0.5),
		LagP95Ticks: pctl(s.lag, 0.95),
		LagP50Beats: pctl(s.lag, 0.5) / float64(max(int(s.ticksPerBeat), 1)),
		MaxLagTicks: s.lagMax,

		Grafts: s.grafts, Prunes: s.prunes,
		Handshakes: s.handshakes, PeerExchanges: s.pxAttempts, SkillSyncs: s.skillSyncs,
		Lookups: s.lookups, Deliveries: s.deliveries, Edges: s.edges,
		DialCapped: s.dialCapped, RejectedState: s.rejectedState,
		SyncMsgs: s.syncMsgs, SyncStates: s.syncStates, PeakInflight: s.maxQueued,

		TasksInjected: s.tasksInjected, TasksLocal: s.tasksLocal,
		TasksRouted: s.tasksRouted, TasksNoWorker: s.tasksNoWorker,
		TasksLost: s.tasksLost, LostReasons: s.lostReasons,
		HopsMean: mean(s.routeHops),
		RouteP50: pctl(s.routeSecs, 0.5), RouteP95: pctl(s.routeSecs, 0.95),
		RouteP99: pctl(s.routeSecs, 0.99),

		Crashed: s.crashed, ConnectivityPre: s.connectBefore,
		ConnectivityMin: s.connectMin, ConnectivityEnd: s.connectEnd,
		ExpireBeats:   float64(s.p.FailureTimeout()) / float64(s.p.Heartbeat()),
		RebuildP50:    pctl(s.rebuildB, 0.5),
		RebuildP95:    pctl(s.rebuildB, 0.95),
		RebuildMax:    pctl(s.rebuildB, 1),
		LostEntries:   s.lostEntries,
		RejoinEntries: s.rejoinEntries,

		StabFullBeats: beatsOf(s, s.stabFull), StabFreshBeats: beatsOf(s, s.stabFresh),
		RecoverFullBeats: s.recoverFull, RecoverFreshBeats: s.recoverFresh,

		SizeOwnGossip: s.sizeOwnGossip, SizeSyncBatch: s.sizeSyncBatch,
		SizeEnvelope: s.sizeEnvelope, SizeAck: s.sizeAck, SizeResult: s.sizeResult,
		SizeCapsRT: s.sizeCapsRT, SizePxRT: s.sizePxRT, SizeID: s.idSize,
	}
	r.IhaveFrames = s.ihaveFrames
	r.IwantFrames = s.iwantFrames
	r.IdontFrames = s.idontFrames
	r.RepairCopies = s.repairCopies
	r.Unrepaired = s.unrepaired
	r.LostInflight = s.lostInflight
	r.MaxSyncBatches = s.maxBatches
	r.DupSuppressions = s.dupSuppressions
	for _, ks := range r.Kinds {
		r.TotalSendBytes += ks.SendBytes
		r.TotalRecvBytes += ks.RecvBytes
	}
	r.Verdict = overall(idle.Verdict, active.Verdict, fail.Verdict)
	s.res = r
	return r
}

// maxLag is the worst view age any node reported, in ticks.
// kindStats attributes the per-node rate to each traffic kind, so the report can say
// not only that a ceiling was missed but by what.
func (s *Sim) kindStats() []KindStat {
	idleSec := int64(max(s.ph.IdleBeats, 1)) * int64(s.ticksPerBeat) * s.tickSeconds()
	activeSec := int64(max(s.ph.ActiveBeats, 1)) * int64(s.ticksPerBeat) * s.tickSeconds()
	out := make([]KindStat, 0, KindCount)
	for k := Kind(0); k < KindCount; k++ {
		var send, recv, aSend, aRecv int64
		for _, nd := range s.nodes {
			send += nd.phaseKind[phaseIdleIdx][k][0]
			recv += nd.phaseKind[phaseIdleIdx][k][1]
			for _, pi := range []int{phaseActiveIdx, phaseFailIdx} {
				aSend += nd.phaseKind[pi][k][0]
				aRecv += nd.phaseKind[pi][k][1]
			}
		}
		out = append(out, KindStat{
			Kind: k, SendBytes: send + aSend, RecvBytes: recv + aRecv,
			KbitIdle:   kbit(send+recv, s.n, idleSec),
			KbitActive: kbit(aSend+aRecv, s.n, activeSec),
		})
	}
	return out
}

func overall(parts ...string) string {
	for _, p := range parts {
		if p == "FAIL" {
			return "FAIL"
		}
	}
	return "PASS"
}

// Meta describes the machine and the commands a run was produced with. Every field
// is filled from the actual environment by the load test, because a load report whose
// environment is a guess cannot be re-run meaningfully.
type Meta struct {
	Machine   string
	GoVersion string
	NProc     string
	Elapsed   string
	Commands  []string

	// FullSyncBoundaries are the measured prices of the model's most load-bearing
	// simplification — how far the analytic full-sync relay lands from walking the flood
	// exactly — at one or more mesh sizes. The list is sorted ascending by Nodes when it
	// is rendered. Empty means not measured, and the boundaries section says so rather
	// than quoting a made-up figure.
	//
	// More than one size is not decoration: the error is size dependent, and a report
	// that quoted only the smallest measurement would describe a ten-percent-scale
	// approximation as a sub-one-percent one.
	FullSyncBoundaries []Boundary
}

// Boundary is the measured price of one modelling assumption: the same run twice, with
// the analytic full-sync relay and with the flood walked exactly.
type Boundary struct {
	Nodes      int
	Beats      int
	Analytic   int64
	Exact      int64
	Percent    float64
	ViewAnalyt float64
	ViewExact  float64
	ViewDelta  float64
	// RunKbit* are the per-node rates over the whole run. The per-phase rate is not
	// comparable between the two billings: an exact flood's tail crosses the phase edge
	// into whichever phase is open when the copy lands, while the analytic relay books
	// every copy of a batch in the batch's own beat. Over the whole run the same bytes
	// agree to well under one percent, which is the number the boundary is about.
	RunKbitAnalyt float64
	RunKbitExact  float64
	RunKbitDelta  float64
	TotalAnalyt   int64
	TotalExact    int64
	TotalDelta    float64
	DelivAnalyt   int64
	DelivExact    int64
	DelivDelta    float64
}

// Markdown renders docs/LOADTEST.md for one run per mesh size.
func Markdown(results []Result, meta Meta) string {
	var b strings.Builder
	b.WriteString("# Нагрузочное тестирование: симуляция membership/routing на " +
		titleSizes(results) + "\n\n")
	b.WriteString("ТЗ 17.3 (нагрузочное тестирование «в симуляции»), ТЗ 22 п.6 (метрики: устойчивость состава, " +
		"скорость обнаружения, уровень служебного трафика, время маршрутизации, поведение при отказе 10 % узлов, " +
		"связность графа) и ТЗ 16.4 (пределы служебного трафика на узел).\n\n")

	b.WriteString("## Как воспроизвести\n\n```bash\n")
	for _, c := range meta.Commands {
		b.WriteString(c + "\n")
	}
	b.WriteString("```\n\n")

	b.WriteString("| Параметр прогона | Значение |\n|---|---|\n")
	row := func(k, v string) { fmt.Fprintf(&b, "| %s | %s |\n", k, v) }
	row("Машина", "`"+meta.Machine+"`")
	row("Версия Go", "`"+meta.GoVersion+"`")
	row("Доступно CPU", meta.NProc)
	row("Wall-clock прогонов этого отчёта", meta.Elapsed)
	if len(results) > 0 {
		row("Seed", fmt.Sprintf("%d — детерминированная генерация identity и workload", results[0].Seed))
		c := results[0].P.Cfg
		row("Конфигурация узлов", fmt.Sprintf("`config.Default()`: heartbeat %v, full_sync %v, failure_timeout %v, "+
			"neighbors min/target/max %d/%d/%d, topic `%s`, max_message_bytes %d",
			c.Discovery.Gossip.Heartbeat.D(), c.Discovery.Gossip.FullSync.D(),
			c.Discovery.Gossip.FailureTimeout.D(), c.Neighbors.Min, c.Neighbors.Target, c.Neighbors.Max,
			c.Discovery.Gossip.Topic, c.Security.MaxMessageBytes))
		gs := results[0].P.GS
		row("Параметры gossipsub", fmt.Sprintf("`pubsub.DefaultGossipSubParams()` (роутер узла собирается без "+
			"overrides): D=%d Dlo=%d Dhi=%d Dlazy=%d heartbeat=%v history=%d/%d IDONTWANT порог %d байт "+
			"(GossipSub v1.2 активен), flood publish выключен",
			gs.D, gs.Dlo, gs.Dhi, gs.Dlazy, gs.HeartbeatInterval, gs.HistoryLength, gs.HistoryGossip,
			gs.IDontWantMessageThreshold))
	}
	b.WriteString("\n")

	b.WriteString("## Сводка по размерам\n\n")
	// The header describes the runs actually passed in, so a single-size rerun does not
	// print two empty columns and a dash where a measurement should be.
	head := "| Метрика |"
	for _, r := range results {
		head += fmt.Sprintf(" %d узлов |", r.Nodes)
	}
	head += "\n|---|" + strings.Repeat("---:|", len(results)) + "\n"
	b.WriteString(head)
	// One cell per run passed in: padding a one-size rerun out to three columns would
	// print a dash where no measurement exists.
	sumRow := func(label string, f func(Result) string) {
		cells := make([]string, len(results))
		for i := range results {
			cells[i] = f(results[i])
		}
		fmt.Fprintf(&b, "| %s | %s |\n", label, strings.Join(cells, " | "))
	}
	sumRow("Служебный трафик в покое, Кбит/с на узел", func(r Result) string { return fmt.Sprintf("%.1f", r.Idle.KbitService) })
	sumRow("Потолок ТЗ 16.4: 100 Кбит/с в покое", func(r Result) string {
		return r.Idle.Verdict + " — норматив " + r.Idle.VerdictRu()
	})
	sumRow("Весь трафик при активной маршрутизации, Кбит/с на узел", func(r Result) string { return fmt.Sprintf("%.1f", r.Active.KbitIn+r.Active.KbitOut) })
	sumRow("в том числе служебный", func(r Result) string { return fmt.Sprintf("%.1f", r.Active.KbitService) })
	sumRow("в том числе задачи", func(r Result) string { return fmt.Sprintf("%.1f", r.Active.KbitTask) })
	sumRow("Потолок ТЗ 16.4: 1 Мбит/с при активности", func(r Result) string {
		return r.Active.Verdict + " — норматив " + r.Active.VerdictRu()
	})
	sumRow("Стабилизация состава: views полны / свежи, heartbeat от старта", func(r Result) string {
		return beatCell(r.StabFullBeats) + " / " + beatCell(r.StabFreshBeats)
	})
	sumRow("Пик за один heartbeat, худший узел, Кбит/с", func(r Result) string { return fmt.Sprintf("%.1f", r.Active.KbitPeak) })
	sumRow("Устойчивость: свежесть views, покой / активность / после отказа", func(r Result) string {
		return fmt.Sprintf("%.3f / %.3f / %.3f", r.FreshIdle, r.FreshActive, r.FreshRecover)
	})
	sumRow("Худшая свежесть за весь прогон", func(r Result) string { return fmt.Sprintf("%.3f", r.FreshMin) })
	sumRow("Полнота views (доля живых узлов в представлении)", func(r Result) string {
		return fmt.Sprintf("%.3f (%.0f из %.0f)", r.ViewFrac, r.ViewSize, r.ViewSize/r.ViewFrac)
	})
	sumRow("Маршрутизируемых соседей на узел (verified handshake)", func(r Result) string { return fmt.Sprintf("%.1f (%.1f%% от views)", r.Routable, 100*r.RoutableFrac) })
	sumRow("Размер mesh gossipsub (фактически, D из конфига сравнивается в параметрах)", func(r Result) string { return fmt.Sprintf("%.1f", r.MeshPeers) })
	sumRow("Соседей на узел (links)", func(r Result) string { return fmt.Sprintf("%.1f", r.Links) })
	sumRow("Обнаружение участника: lag views, медиана heartbeat", func(r Result) string { return fmt.Sprintf("%.1f", r.LagP50Beats) })
	sumRow("то же в gossipsub-тикаках: p50 / p95", func(r Result) string { return fmt.Sprintf("%.0f / %.0f", r.LagP50Ticks, r.LagP95Ticks) })
	sumRow("Время маршрутизации задачи p50 / p95 / p99, c", func(r Result) string {
		return fmt.Sprintf("%.0f / %.0f / %.0f", r.RouteP50, r.RouteP95, r.RouteP99)
	})
	sumRow("Hops до исполнителя, среднее", func(r Result) string { return fmt.Sprintf("%.2f", r.HopsMean) })
	sumRow("Задач: инжектировано / локально / делегировано / без исполнителя / потеряно", func(r Result) string {
		return fmt.Sprintf("%d / %d / %d / %d / %d", r.TasksInjected, r.TasksLocal, r.TasksRouted, r.TasksNoWorker, r.TasksLost)
	})
	sumRow("Связность графа: покой → минимум при отказе → конец фазы", func(r Result) string {
		return fmt.Sprintf("%.4f → %.4f → %.4f", r.ConnectivityPre, r.ConnectivityMin, r.ConnectivityEnd)
	})
	sumRow("Выбывание мёртвых из views (ожидание по failure_timeout), heartbeat", func(r Result) string { return fmt.Sprintf("%.0f", r.ExpireBeats) })
	sumRow("Восстановление views после отказа p50 / p95 / max, heartbeat", func(r Result) string {
		return fmt.Sprintf("%.1f / %.1f / %.1f", r.RebuildP50, r.RebuildP95, r.RebuildMax)
	})
	sumRow("Сходимость после отказа: views полны / свежи, heartbeat от момента отказа", func(r Result) string {
		return beatCell(r.RecoverFullBeats) + " / " + beatCell(r.RecoverFreshBeats)
	})
	sumRow("Записей views: принято впервые / выбыло по expiry", func(r Result) string {
		return fmt.Sprintf("%d / %d", r.RejoinEntries, r.LostEntries)
	})
	sumRow("Длительность прогона (wall clock машины отчёта)", func(r Result) string {
		if r.Wall <= 0 {
			return "не замерялась"
		}
		return r.Wall.Round(100 * time.Millisecond).String()
	})
	sumRow("Пик RSS процесса после этого прогона", func(r Result) string { return rssCell(r) })
	if note := rssNote(results); note != "" {
		b.WriteString("\n" + note)
	}
	b.WriteString("\n")

	for i := range results {
		b.WriteString(results[i].Section())
	}
	b.WriteString(ModelSectionWith(results, meta.FullSyncBoundaries))
	return b.String()
}

// beatCell renders a heartbeat count, spelling out the case where the mesh never got
// there inside the measurement window instead of printing a bare -1.
func beatCell(v float64) string {
	if v < 0 {
		return "не достигнуто за фазу"
	}
	return fmt.Sprintf("%.1f", v)
}

// rssCell renders a peak-RSS reading, or the absence of one. VmHWM is a high-water mark
// for the whole process rather than for one subtest, so in a multi-size run the largest
// figure is the only one that describes the run; that is stated once, after the table,
// instead of being footnoted in every cell.
func rssCell(r Result) string {
	if r.PeakRSSKb <= 0 {
		return "не замерялся"
	}
	return fmt.Sprintf("%.2f GiB", float64(r.PeakRSSKb)/1048576)
}

// SelfPeakRSSKb reads VmHWM from the calling process's own /proc entry. It is the
// harness's memory, not a simulated node's: the model has no per-node allocation to
// attribute, and pretending otherwise would put a machine number in a protocol column.
// Returns 0 where /proc has no such line.
func SelfPeakRSSKb() int64 {
	b, err := os.ReadFile("/proc/self/status")
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(b), "\n") {
		if rest, ok := strings.CutPrefix(line, "VmHWM:"); ok {
			n, err := strconv.ParseInt(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(rest), " kB")), 10, 64)
			if err != nil {
				return 0
			}
			return n
		}
	}
	return 0
}

// rssNote is the honesty line about what the RSS column can and cannot say.
func rssNote(results []Result) string {
	var newest *Result
	for i := range results {
		if results[i].PeakRSSKb > 0 {
			newest = &results[i]
		}
	}
	if newest == nil {
		return ""
	}
	return fmt.Sprintf("Память — `/proc/<pid>/status:VmHWM` процесса теста, то есть высокий "+
		"водоразмер на весь процесс, а не на один размер: в прогоне из нескольких размеров "+
		"последняя колонка и есть пик всего прогона (%s после %d узлов). Go при этом не "+
		"возвращает освобождённое арене сразу, поэтому цифра описывает модель (её очередь "+
		"доставок, битмапы достижимости и накопленные series), а не то, сколько памяти "+
		"потребовал бы реальный узел.\n",
		rssCell(*newest), newest.Nodes)
}

// Section renders one size's detail: verdict, per-kind attribution, membership
// behaviour, tasks, failure behaviour and the measured wire costs.
func (r Result) Section() string {
	var b strings.Builder
	fmt.Fprintf(&b, "## %d узлов: подробно\n\n", r.Nodes)
	b.WriteString("### Вердикт по ТЗ 16.4\n\n")
	b.WriteString("| Фаза | Измерено на узел, Кбит/с | Потолок | Оценка по ТЗ 16.4 | Пояснение |\n|---|---:|---:|---|---|\n")
	fmt.Fprintf(&b, "| Покой (служебный трафик) | %.1f | %.0f | **%s — норматив %s** | %s |\n",
		r.Idle.KbitService, r.Idle.Ceiling, r.Idle.Verdict, r.Idle.VerdictRu(), r.Idle.Detail)
	fmt.Fprintf(&b, "| Активная маршрутизация (весь трафик) | %.1f | %.0f | **%s — норматив %s** | %s |\n",
		r.Active.KbitIn+r.Active.KbitOut, r.Active.Ceiling, r.Active.Verdict, r.Active.VerdictRu(), r.Active.Detail)
	fmt.Fprintf(&b, "| Отказ 10 %% (весь трафик) | %.1f | %.0f | **%s — норматив %s** | %s |\n",
		r.Failure.KbitIn+r.Failure.KbitOut, r.Failure.Ceiling, r.Failure.Verdict, r.Failure.VerdictRu(), r.Failure.Detail)
	fmt.Fprintf(&b, "\n**Итог по %d узлам: %s (%s)**\n\n", r.Nodes, r.Verdict,
		map[string]string{"PASS": "все три фазы в пределах ТЗ 16.4",
			"FAIL": "как минимум одна фаза вне пределов ТЗ 16.4"}[r.Verdict])

	b.WriteString("### Из чего складывается трафик (Кбит/с на узел)\n\n")
	b.WriteString("| Категория | Покой | Активность + отказ |\n|---|---:|---:|\n")
	for _, k := range r.Kinds {
		if k.SendBytes == 0 && k.RecvBytes == 0 {
			continue
		}
		fmt.Fprintf(&b, "| %s | %.1f | %.1f |\n", k.Kind, k.KbitIdle, k.KbitActive)
	}

	b.WriteString("\n### Механика протокола (за всё время прогона)\n\n")
	b.WriteString("| Событие | Счётчик |\n|---|---:|\n")
	for _, e := range []struct {
		name string
		v    int64
	}{
		{"доставок публикаций (gossipsub)", r.Deliveries},
		{"GRAFT", r.Grafts},
		{"PRUNE", r.Prunes},
		{"IHAVE-кадров", r.IhaveFrames},
		{"IDONTWANT-кадров", r.IdontFrames},
		{"capabilities round trip (handshakes)", r.Handshakes},
		{"peer-exchange RPC", r.PeerExchanges},
		{"skills-sync RPC", r.SkillSyncs},
		{"skill-lookup RPC", r.Lookups},
		{"дуг графа соседей", r.Edges},
		{"отказов диала из-за neighbors.max", r.DialCapped},
		{"отклонённых чужих состояний (AllowDelegationTo)", r.RejectedState},
		{"batch full-sync", r.SyncMsgs},
		{"PeerState в full-sync", r.SyncStates},
		{"максимум неотданных доставок в очереди", r.PeakInflight},
		{"IWANT-кадров", r.IwantFrames},
		{"копий, дотянутых IHAVE/IWANT", r.RepairCopies},
		{"не дотянутых (у узла нет живого соседа)", r.Unrepaired},
		{"копий подавлено дедупликацией (граница 2)", r.DupSuppressions},
		{"байт не дошло (отправка в мёртвый узел, конец окна)", r.LostInflight},
		{"всего байт отправлено", r.TotalSendBytes},
		{"всего байт принято", r.TotalRecvBytes},
		{"максимум пачек full-sync на узел за beat", int64(r.MaxSyncBatches)},
	} {
		fmt.Fprintf(&b, "| %s | %d |\n", e.name, e.v)
	}

	b.WriteString("\n### Стоимость протокольных сообщений (измерена proto.Marshal)\n\n")
	b.WriteString("| Сообщение | Байт |\n|---|---:|\n")
	fmt.Fprintf(&b, "| heartbeat-публикация (1 PeerState + pubsub-конверт + кадр) | %d |\n", r.SizeOwnGossip)
	fmt.Fprintf(&b, "| batch full-sync (≤%d PeerState) | %d |\n", fullSyncBatchStates, r.SizeSyncBatch)
	fmt.Fprintf(&b, "| gossipsub message id (from+seqno) | %d |\n", r.SizeID)
	fmt.Fprintf(&b, "| capabilities round trip | %d |\n", r.SizeCapsRT)
	fmt.Fprintf(&b, "| peer-exchange ответ (%d записи) | %d |\n", peerExchangeAnswerLimit, r.SizePxRT)
	fmt.Fprintf(&b, "| TaskEnvelope | %d |\n", r.SizeEnvelope)
	fmt.Fprintf(&b, "| TaskAck | %d |\n", r.SizeAck)
	fmt.Fprintf(&b, "| TaskResult | %d |\n", r.SizeResult)

	fmt.Fprintf(&b, "\n### Параметры workload этого прогона\n\n")
	fmt.Fprintf(&b, "Каталог навыков: `%s`; доля узлов только с \"general\": %.2f; вероятность навыка у "+
		"специализированного узла: %.2f; задача каждые %d heartbeat на узел; payload %d байт; "+
		"исполнение %d tick; фазы %d/%d/%d heartbeat; отказ %d%%.\n",
		strings.Join(r.P.SkillCatalog, ", "), r.P.GeneralShare, r.P.SkillShare, r.Ph.InjectEveryBeats,
		r.P.TaskPayloadBytes, r.P.ExecTicks, r.Ph.IdleBeats, r.Ph.ActiveBeats, r.Ph.FailureBeats,
		int(r.Ph.CrashFraction*100))
	if len(r.LostReasons) > 0 {
		keys := make([]string, 0, len(r.LostReasons))
		for k := range r.LostReasons {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s: %d", k, r.LostReasons[k]))
		}
		fmt.Fprintf(&b, "\nПричины потерь задач — %s.\n", strings.Join(parts, "; "))
	}
	b.WriteString("\n")
	return b.String()
}

// ModelSectionWith renders the boundaries of the model together with the numbers that
// measure them. It is separate from ModelSection because a load-test run carries a
// measured analytic-versus-exact comparison, while a bare rendering of the prose does
// not — and then it says so, rather than quoting a figure nobody measured.
func ModelSectionWith(results []Result, bs []Boundary) string {
	return modelProse() + "\n### Границы в числах\n\n" + boundaryNumbers(results, bs)
}

// ModelSection renders the boundaries section without a measured comparison.
func ModelSection(results []Result) string {
	return ModelSectionWith(results, nil)
}

// boundaryNumbers quantifies the claims in the notes above that are measurable: how far
// the analytic full-sync relay is from the exact walk and how that error grows with the
// mesh, how many frames the dedupe rule withholds, and how fast the per-node service
// traffic actually grows with N. Each reading states what it is a ratio of, because the
// baseline differs from claim to claim.
func boundaryNumbers(results []Result, bs []Boundary) string {
	var s strings.Builder
	bs = sortedBoundaries(bs)
	if len(bs) > 0 {
		fmt.Fprintf(&s, "Одно и то же исполнение, тот же seed, idle-фаза %d heartbeat; ретрансляция "+
			"пачек full-sync посчитана двумя способами — аналитически (одна копия на подписчика) и "+
			"точным обходом флуда. Замер сделан на %d размерах сети, потому что погрешность этой "+
			"замены зависит от размера:\n\n", bs[0].Beats, len(bs))
		s.WriteString("| Узлов | Байт full-sync: аналитика | точный обход | расхождение | " +
			"Кбит/с на узел за прогон: аналитика | точный обход | расхождение | " +
			"Полнота views: аналитика | точный обход | расхождение |\n")
		s.WriteString("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
		for _, b := range bs {
			fmt.Fprintf(&s, "| %d | %d | %d | %+.2f%% | %.1f | %.1f | %+.2f%% | %.1f | %.1f | %+.2f%% |\n",
				b.Nodes, b.Analytic, b.Exact, b.Percent,
				b.RunKbitAnalyt, b.RunKbitExact, b.RunKbitDelta,
				b.ViewAnalyt, b.ViewExact, b.ViewDelta)
		}
		s.WriteString("\nСтрок «по фазам» в этой таблице нет намеренно: точный обход доносит хвост " +
			"флуда за границу фазы — в ту фазу, на тик которой копия реально прибыла, — а аналитика " +
			"ставит все копии пачки в beat самой пачки. По фазам эти два способа расходятся сильнее, " +
			"чем за прогон целиком, и сравнивать их по фазам некорректно.\n\n")
		signNote := ""
		if bs[0].Percent*bs[len(bs)-1].Percent < 0 {
			signNote = "Знак меняется по ходу: допуск то занижает, то завышает расход. "
		}
		fmt.Fprintf(&s, "Читать это надо так: расхождение по байтам full-sync идёт от %s при %d узлах к "+
			"%s при %d. %s",
			signed(bs[0].Percent), bs[0].Nodes,
			signed(bs[len(bs)-1].Percent), bs[len(bs)-1].Nodes,
			signNote)
		// The completeness claim is stated only for the sizes that support it, since it is
		// the claim a reader is most likely to rely on: «the approximation moves bytes, not
		// membership» is true at one scale and false at another.
		const viewTol = 0.02
		small, large := bs[0], bs[len(bs)-1]
		switch {
		case absPctF(small.ViewDelta) <= viewTol && absPctF(large.ViewDelta) > viewTol:
			fmt.Fprintf(&s, "Полноту состава допуск не трогает до %d узлов (%s), а на %d расходится уже "+
				"заметно (%s): ", lastSizeWithin(bs, viewTol, func(b Boundary) float64 {
				return b.ViewDelta
			}), signed(small.ViewDelta), large.Nodes, signed(large.ViewDelta))
		case absPctF(large.ViewDelta) <= viewTol:
			fmt.Fprintf(&s, "Полноту состава допуск не трогает ни при одном из замеренных размеров "+
				"(наибольшее расхождение — %s): ", signed(largestAbs(bs, func(b Boundary) float64 {
				return b.ViewDelta
			})))
		default:
			fmt.Fprintf(&s, "Полноту состава допуск трогает уже при наименьшем замеренном размере (%s): ",
				signed(small.ViewDelta))
		}
		s.WriteString("аналитика не доносит содержимое пачки, и состав держится только на " +
			"heartbeat-публикациях, которые обходятся точно, — при полном mesh-покрытии это работает, " +
			"пока view не начнёт упираться в expiry.\n\n")
		s.WriteString("На вердикт по ТЗ 16.4 это не влияет ни при каком замеренном размере: превышение " +
			"потолка в этих прогонах измеряется разами, а не процентами. Влияет оно на то, как читать " +
			"наклон трафика: аналитика завышает и уровень, и рост, поэтому степень роста служебного " +
			"приёма смотрят не по границе 5, а по строке «он же, делённый на N» ниже.\n\n")
	} else {
		s.WriteString("Расхождение аналитической ретрансляции full-sync с точным обходом в этом " +
			"прогоне не замерялось. Оно измеряется быстрым тестом без тега `load`:\n\n" +
			"```bash\ngo test -count=1 -run TestFullSyncAnalyticVersusExactFlood ./internal/simulator/\n```\n\n" +
			"Тест прогоняет ту же сборку дважды — с точным обходом флуда (`exactRelay`) и с " +
			"аналитикой — и печатает расхождение в процентах; прогон под тегом `load` подставляет " +
			"его в этот раздел для нескольких размеров сети.\n\n")
	}
	if len(results) > 0 {
		s.WriteString("| Показатель | " + strings.Join(sizesHeader(results), " | ") + " |\n")
		s.WriteString("|---|" + strings.Repeat("---:|", len(results)) + "\n")
		row := func(label string, f func(Result) string) {
			cells := make([]string, 0, len(results))
			for _, r := range results {
				cells = append(cells, f(r))
			}
			fmt.Fprintf(&s, "| %s | %s |\n", label, strings.Join(cells, " | "))
		}
		row("копий подавлено дедупликацией (граница 2)", func(r Result) string { return fmt.Sprintf("%d", r.DupSuppressions) })
		// Expressed as a multiple of the delivery count, not a percentage of it: the model
		// suppresses several copies per delivery, so a percent column would show values
		// above 100 % and read as an arithmetic error.
		row("то же, в разах от числа доставок", func(r Result) string {
			return fmt.Sprintf("%.2f", float64(r.DupSuppressions)/float64(max64(r.Deliveries, 1)))
		})
		row("служебный приём на узел в покое, Кбит/с", func(r Result) string {
			return fmt.Sprintf("%.1f", r.Idle.KbitService)
		})
		row("он же, делённый на N", func(r Result) string {
			return fmt.Sprintf("%.3f", r.Idle.KbitService/float64(r.Nodes))
		})
		row("байт не дошло (отправка в мёртвый узел, конец окна)", func(r Result) string {
			return fmt.Sprintf("%d (%.2f%%)", r.LostInflight,
				100*float64(r.LostInflight)/float64(max64(r.TotalSendBytes, 1)))
		})
		s.WriteString("\n" + growthSentence(results))
	}
	return s.String()
}

// growthSentence checks boundary 5 against the measured numbers instead of asserting it:
// the note claims that every node pays for every node's publication, which predicts a
// per-node service rate growing at least linearly with N. Whether it grows exactly
// linearly or faster is a measurement, and the difference matters to anyone extrapolating
// the table, so the sentence is built from the reading rather than from the claim.
func growthSentence(results []Result) string {
	exp := growthExponent(results)
	switch {
	case exp == 0:
		return "Строка «он же, делённый на N» — проверка границы 5, и для неё нужно минимум два " +
			"размера сети; в этом отчёте он один, поэтому проверка не производилась.\n"
	case exp < 0:
		return "Строка «он же, делённый на N» — проверка границы 5, и она не сводится к показателю " +
			"степени: с ростом сети делённый на N служебный приём уменьшился, то есть mesh и " +
			"IDONTWANT погасили больше копий, чем добавилось издателей. Об одном механизме границы 5 " +
			"это говорит прямо, о степени роста — нет.\n"
	}
	head := "Строка «он же, делённый на N» — проверка границы 5: при линейном росте она давала бы " +
		"константу. Измеренный показатель степени — " + fmt.Sprintf("%.2f", exp) + "; "
	tail := "он равен единице, то есть рост ровно линейный, как и говорит граница 5. "
	switch {
	case exp > 1.15:
		tail = "он больше единицы, поэтому граница 5 описывает механизм (каждый узел платит за " +
			"каждую публикацию каждого узла), а не конкретную степень. С ростом сети растёт и ширина " +
			"вью на узел, а с ней и число пачек full-sync на beat — см. «максимум пачек full-sync на " +
			"узел за beat» в разделе «Механика протокола»: публикация дороже, когда в ней есть что " +
			"нести. "
	case exp < 0.85:
		tail = "он меньше единицы: mesh-ретрансляция и IDONTWANT гасят часть копий быстрее, чем " +
			"растёт число издателей. "
	}
	return head + tail + "Именно этот член, а не качество реализации, определяет, где числа " +
		"пересекают потолок ТЗ 16.4.\n"
}

// growthExponent is the log-log slope of the idle per-node service rate between the
// smallest and the largest measured mesh. It returns 0 when there is only one size — so a
// caller can say "not measured" instead of dividing by a zero denominator — and −1 when no
// slope is meaningful (identical sizes, or a rate that fell where the width grew).
func growthExponent(results []Result) float64 {
	if len(results) < 2 {
		return 0
	}
	first, last := results[0], results[len(results)-1]
	if first.Nodes == last.Nodes || first.Idle.KbitService <= 0 || last.Idle.KbitService <= 0 {
		return -1
	}
	rate := math.Log(last.Idle.KbitService / first.Idle.KbitService)
	width := math.Log(float64(last.Nodes) / float64(first.Nodes))
	if rate < 0 {
		return -1
	}
	return rate / width
}

// sizesHeader lists the mesh sizes as table columns.
func sizesHeader(results []Result) []string {
	out := make([]string, 0, len(results))
	for _, r := range results {
		out = append(out, fmt.Sprintf("%d узлов", r.Nodes))
	}
	return out
}

// titleSizes spells the mesh sizes out for the document title, falling back to the ТЗ
// wording when a caller renders a report with no runs in it — an empty title would read as
// a broken document rather than as an unused renderer.
func titleSizes(results []Result) string {
	if len(results) == 0 {
		return "100 / 500 / 1000 узлов"
	}
	out := make([]string, 0, len(results))
	for _, r := range results {
		out = append(out, strconv.Itoa(r.Nodes))
	}
	return strings.Join(out, " / ") + " узлов"
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

// sortedBoundaries returns the cross-check readings by ascending mesh size, so the
// rendered trend reads as a trend regardless of the order the harness measured them in.
func sortedBoundaries(bs []Boundary) []Boundary {
	out := append([]Boundary(nil), bs...)
	sort.Slice(out, func(a, b int) bool { return out[a].Nodes < out[b].Nodes })
	return out
}

// signed formats a percentage difference with its sign, which is the part a reader needs
// to know whether the model's assumption was optimistic or pessimistic.
func signed(v float64) string { return fmt.Sprintf("%+.2f%%", v) }

// lastSizeWithin answers "up to which measured mesh size did this error stay under tol":
// the sizes are sorted, and the claim is about the run of small sizes at the start, not
// about the minimum over all of them — a non-monotonic reading must not extend the claim.
// Returns the size before the first breach, or the smallest measured size when the very
// first reading already breaches (so the caller prints "up to N" rather than "up to 0").
func lastSizeWithin(bs []Boundary, tol float64, f func(Boundary) float64) int {
	if len(bs) == 0 {
		return 0
	}
	for i, b := range bs {
		if absPctF(f(b)) > tol {
			if i == 0 {
				return bs[0].Nodes
			}
			return bs[i-1].Nodes
		}
	}
	return bs[len(bs)-1].Nodes
}

// absPctF is math.Abs without importing math for one call.
func absPctF(v float64) float64 {
	if v < 0 {
		return -v
	}
	return v
}

// largestAbs returns the reading whose magnitude is greatest, so a sentence can quote the
// worst case rather than the last one.
func largestAbs(bs []Boundary, f func(Boundary) float64) float64 {
	var best float64
	for _, b := range bs {
		if v := f(b); absPctF(v) > absPctF(best) {
			best = v
		}
	}
	return best
}

// modelProse is the qualitative half of the boundaries section.
func modelProse() string {
	return fmt.Sprintf(`
## Что модель воспроизводит

- **Протокол membership — целиком, по коду internal/discovery**: одна PeerState на
  heartbeat (Membership.Publish); полный синк вью по пачкам ровно из %d состояний,
  разнесённые heartbeat/8 (Membership.PublishFull); приём с двумя правилами из
  gossip.go — «чужое состояние только от пира, которому мы доверяем маршрутизацию»
  (policy.AllowDelegationTo) и «новое не перекрывается старым»; expiry по
  failure_timeout (expireLoop); все лимиты прочитаны из конфигурации по умолчанию, не
  продублированы литералами.
- **gossipsub так, как его собирает узел**: mesh из D пиров, публикация уходит
  только в mesh (flood publish в роутере узла выключен), получатель, уже принявший
  сообщение, не ретранслирует его, IHAVE advertises окно HistoryGossip, IDONTWANT
  при сообщении от IDontWantMessageThreshold байт (в этом пороге GossipSub v1.2 и
  активен), GRAFT/PRUNE с backoff, peer-exchange в PRUNE, кандидатов mesh берёт из
  подключённых пиров — направление ребра значимо.
- **Байты честно**: каждый размер — proto.Marshal настоящих сообщений из
  gen/zeptomesh/v1 + protobuf-конверт pubsub (From/Seqno/Topic/Signature 64 байта,
  Ed25519-ключ в peer id уже embedded, поэтому Key пустой) + uvarint-префикс кадра
  из internal/p2p/framing.go. Стоимость каждого типа выведена в таблице выше и
  пересчитывается вместе с wire-форматом.
- **Решение маршрутизации — настоящим кодом**: routing.Table.Select с настоящими
  весами (0.40/0.25/0.20/0.10/0.05), множителем 0.85 за «не подключён», фильтром
  навыков и фильтром доверия; безопасность — настоящий security.Policy в режиме
  limited. Кандидат, которому уходит задача, это тот же кандидат, что выбрал бы узел.
- **Отказ как тихую потерю heartbeat**: узел не шлёт «left», соседи узнают о нём
  только тем, что состояние перестало приходить и expiry наступило. Это тот самый
  механизм, для которого ТЗ 22 п.6 просит измерить время восстановления.

## Что модель НЕ воспроизводит

- **TCP/TLS(noise)-рукопожатие libp2p и стоимость установления соединения** — байт
  и задержка handshake не учтены ни в одной строке отчёта.
- **NAT, relay, hole punching, достижимость адресов** — адреса синтетические
  (/ip4/10.x.y.z/tcp/4001/p2p/<id>, как их рендерит node.DiscoverableAddrs), но
  пакеты никуда не летят.
- **Пропускную способность канала, задержку, джиттер, потери** — доставка
  происходит дискретно по gossipsub-тикам; один ребро = один тик. Это единственная
  замена задержки, и она видна отдельно в метрике hops/lag.
- **Очереди и насыщение** — модель не знает, что такое backpressure: при
  приближении к пределу канала реальный узел начнёт терять и откладывать, а не
  платить ровно столько же. Поэтому превышение потолка в этой модели означает
  «провал и в реальности», а близость к нему не означает «в реальности всё будет
  хорошо».
- **CPU, память, диск, GC, очередь задач, размер хранилища реального узла** — не
  измеряются данной моделью: узел здесь — структура данных, а не процесс. Из machine
  numbers в отчёте есть только стоимость самого прогона (wall clock и VmHWM процесса
  теста), и она описывает модель, а не узел: см. строки «Длительность прогона» и «Пик
  RSS» в сводке.
- **connmgr, reconnect backoff транспорта, сегментация** — не измеряется данной
  моделью; связность считается по графу соседей.
- **Реальный профиль нагрузки и реальный LLM** — исполнение это
  ExecTicks heartbeat, а не сессия PicoClaw (офлайн-заглушка из конфига отвечает за
  50 мс, что beat-квантованная модель разрешить не может); каталог навыков и доли
  специализации — workload-предположение, зафиксированное в DefaultParams. При
  другом каталоге числа маршрутизации будут другими.
- **DHT-обход целиком** — DHT участвует как источник пира-обмена по запросу, не как
  полноценная сеть провайдеров.
- **Шифрование и верификация подписей** — подписи есть в размерах сообщений
  (64 байта на подпись, реальная длина), но crypto-операции
  не исполняются.

Там, где метрика этой моделью не измерима, в отчёте стоит «не измеряется данной
моделью», а не оцененное число.

## Границы, о которых надо знать, читая таблицу

1. Модель не перебирает доставки O(N²): ретрансляция по mesh и дедупликация по
   принятым сообщениям воспроизются дословно, поэтому публикация стоит примерно
   «одна доставка на подписчика», а не «одна доставка на ребро». Модель, которая
   считала бы каждую публикацию доставленной каждому узлу, показала бы шторм,
   которого протокол не создаёт; модель, считала бы только mesh-рёбра, показала бы
   недоставленные состояния.
2. Дедупликация в модели подавляет второй экземпляр ещё на этапе постановки в
   очередь отправителем (gossipsub пишет оба экземпляра в один RPC-кадр тому же
   пиру и тому же heartbeat). Реальный роутер доставит дубликат и отбросит его
   принявшим узлом — то есть на один кадр больше. Разница равна числу треугольников
   в mesh степени D, она только занижает трафик, и она не скрывается: см. счётчик
   доставок выше.
3. Проложенность «general» во всех узлах сделала бы маршрутизацию неизмеримой
   (routing.skillsMatch удовлетворяется этим навыком, и любая задача ушла бы в
   один хоп). Поэтому каталог навыков в модели гетерогенный — это нагрузка, а не
   факт протокола, и он зафиксирован в таблице параметров.
4. Ретрансляция пачки full-sync считается аналитически, а не обходом флуда.
   Публикация heartbeat (одна PeerState) проходит по mesh доставка за доставкой, и
   каждая копия поставлена на счёт двум концам. Пачка полного синка — до %d состояний
   в одном сообщении, её ширину в байтах см. в таблице размеров выше — получает первый
   хоп точно так же, а дальше ей биллится «одна копия на подписчика»: при таком размере
   IDONTWANT гасит дубли, а точный обход стоил бы Θ(N²) доставок на beat (на тысяче
   узлов — десятки миллионов). Погрешность этой замены измерена и приведена в разделе
   «Границы в числах»; на состав она не влияет, потому что состояния в пачке
   получатель уже видел в heartbeat-публикациях, которые обходятся точно.
5. Протокол ограничения трафика (mesh, дедупликация, IDONTWANT, пачки по %d)
   оптимизирует именно служебный трафик membership-топика; при N узлов каждый узел
   получает копию каждой публикации, поэтому служебный приём на узел растёт
   линейно с N. Это свойство дизайна топика, а не артефакт модели, и именно оно
   определяет, где числа в таблице пересекают потолок ТЗ 16.4.
`, fullSyncBatchStates, fullSyncBatchStates, fullSyncBatchStates)
}
